### ISSUE TITLE
SSH Key Setting Empty View

### ISSUE THREAD

**Issue by wmorgue** [xibbon/LaTerminal#11]
Hello 🤝
Found a design flaw. When I create a new ssh key, I see an empty view and hidden sidebar.
Maybe we should remove the sidebar and put the view directly on the screen?

Watch the video: 

https://user-images.githubusercontent.com/24982084/191688066-88604e88-579f-4106-85b4-01c9903dc035.MOV

La Terminal `1.0.2` from App Store | iPad Pro M1 `iPadOS 15.7`

**Comment by migueldeicaza** [comment]
Thank you for this recording and the bug report, this will be fixed in the upcoming release.
