### ISSUE TITLE
Bug with navigation in Terminal grid view

### ISSUE THREAD

**Issue by wmorgue** [xibbon/LaTerminal#12]
Hello 🤝

When navigating from the Terminals tab, I noticed a bug. Clicking to go immediately does not work.
Watch the video for a better understanding:

https://user-images.githubusercontent.com/24982084/191689317-b4e193c4-ad24-49cd-94db-a7d4e1ac1ce2.MOV

La Terminal `1.0.2` from App Store | iPad Pro M1 `iPadOS 15.7`

**Comment by migueldeicaza** [comment]
This bug has been fixed
