### ISSUE TITLE
Feature: Allow other fonts to be used.

### ISSUE THREAD

**Issue by bundy845** [xibbon/LaTerminal#17]
Most of the servers on my local network that I ssh into have [Oh My Posh](https://ohmyposh.dev) installed. Those configurations rely on special fonts, such as [Nerd Fonts](https://www.nerdfonts.com). I have the app Fontcase installed on my phone. Via it, I installed Nerd Fonts and these are available in some apps but LaTerminal doesn't recognize fonts installed. Is it possible to use this method or another one? Having those icons in my Oh My Posh prompts would be very handy.

**Comment by wmorgue** [comment]
Same for me. Nerd Fonts doesn’t recognize.
![Screenshot 2022-09-24 at 09 31 17](https://user-images.githubusercontent.com/24982084/192083576-9ff4aa59-c000-4c32-b443-4c89581d2ba7.png)

**Comment by migueldeicaza** [comment]
Question, when you use Nerd Fonts on your phone, do you need to fully select one of those fonts to use, or is there some sort of fallback where you have a primary font, and then it falls back to the Nerd Font you installed?

**Comment by wmorgue** [comment]
I'm not sure I understand you right. The font is installed on the macOS:

```
❯ brew ls | rg nerd
font-hack-nerd-font
```

I use a `LaTerminal` iPadOS version and by default  selected  the`SF Mono`.

**Comment by migueldeicaza** [comment]
This has been implemented, it should be available soon (I think AppStore review is closed for the weekend)
