### ISSUE TITLE
Bug: single UP arrow tap triggers double jump in command history

### ISSUE THREAD

**Issue by rnsc** [xibbon/LaTerminal#19]
So, I'll classify this as a bug, even though you could definitely argue it's a user issue.

The double jump only happens when my finger sits milliseconds too long on the up arrow.
Leaving the up arrow pressed goes very fast through the command history once it's pressed.

Because this is happening to me more than 1 time per session (especially because I'm just testing the application these past few days), I'm wondering if there could be a small delay (after initial press) added so that the first time you press up or down you're not automatically going too fast up or down. I think it's a good speed for left and right though.

**Comment by migueldeicaza** [comment]
On it!

**Comment by migueldeicaza** [comment]
Thank you for the bug fix @iOSappssolutions !
