### ISSUE TITLE
Feature Request: Add Mosh Support

### ISSUE THREAD

**Issue by jamieshorten** [xibbon/LaTerminal#21]
Add support for [Mosh](https://github.com/mobile-shell/mosh) to better support poor and/or intermittent connections.

**Comment by migueldeicaza** [comment]
It is unlikely that we would add Mosh support at this point due to the license of it, but we have an alternative that provides the same functionality:

https://blog.xibbon.com/solving-background-disconnect-issues-on-ios-with-el/
