### ISSUE TITLE
blog posts have no byline

### ISSUE THREAD

**Issue by colbyrussell** [xibbon/LaTerminal#37]
The first (and currently only) blog post is written in first person; who is "I"?

Steps to reproduce:

1. visit <https://xibbon.com/terminal/2022/09/21/welcome-to-la-terminal.html>
2. read the first sentence that begins, "In 1992, I fell in love with Unix and Linux[...]"
3. look for author attribution at the top of the page
4. scroll to the bottom of the page
5. look for author attribution at the end of the article

Expected results:

I know who is speaking, either after step 3 or step 5.

Actual results:

I find no byline.  I don't know who is speaking.

**Comment by migueldeicaza** [comment]
Oh, we need to fix this.

**Comment by migueldeicaza** [comment]
It should be there now
