### ISSUE TITLE
Support ANSI OSC52 to copy content remotely

### ISSUE THREAD

**Issue by aymanbagabas** [xibbon/LaTerminal#38]
A wide range of desktop terminals now support ANSI OSC52 escape sequence to manipulate the clipboard. Adding support for this means the user can copy content remotely using the escape sequence.

**Comment by migueldeicaza** [comment]
This is a fine idea, let me research whether this is considered a security problem or not.   I recall xterm put this behind some flag.

**Comment by migueldeicaza** [comment]
(Btw, SwiftTerm the library already supports this, this is a matter of wiring up the request copyClipboard, and determining what UI is necessary for it)

**Comment by migueldeicaza** [comment]
This has been implemented, and will be in the release after the next (1.0.11)
