### ISSUE TITLE
Monitoring showing wrong CPU usage on dashboard

### ISSUE THREAD

**Issue by igorkulman** [xibbon/LaTerminal#55]
On my Ubuntu 22.04.1 LTS server ad idle I get about 0.16% - 0.20% cpu load as shown in htop

<img width="889" alt="Screenshot 2023-02-16 at 21 50 27" src="https://user-images.githubusercontent.com/4746070/219485567-58f545a9-3f00-44e3-9ac7-63f7450e5d55.png">

this shows correctly in the monitoring in the ssh session

![IMG_6135](https://user-images.githubusercontent.com/4746070/219485688-d2bdd70d-03bf-4457-8194-6f50d6f9898c.PNG)

but on dashboard the CPU loads shows as 17% instead of 0.17%

![IMG_6136](https://user-images.githubusercontent.com/4746070/219485816-0d7792a2-24e2-445b-b971-20832651b711.PNG)

**Comment by migueldeicaza** [comment]
Bummer, this one is trickier, on my machine the parsing is correct.

Would you mind showing me what this outputs when the data is out of sync?

cat /proc/loadavg

**Comment by migueldeicaza** [comment]
Oh actually, on closer inspection, I dont think it is a but in La Terminal.

LoadAverages go from 0 to 1.0 to represent 0 to 100% utilization.   Higher numbers than 1 mean that you are over-taxes (ie, load average of 2 means that you have twice as much work to do as CPU time).

So when your load average shows 0.17 it is 17% utilization
