### ISSUE TITLE
SSH Agent Forwarding

### ISSUE THREAD

**Issue by JosephHill** [xibbon/LaTerminal#67]
SSH agent forwarding would enable La Terminal users to use the keys configured locally in La Terminal when connecting to other hosts from an initial server connection.  I.e., once connected to a host in La Terminal, users can ssh from that host directly to another host without having to install their private keys on the first first host).

**Comment by migueldeicaza** [comment]
SSH Agent forwarding is now available to TestFlight users to take out for a spin.
