### ISSUE TITLE
Feature: Add Host Grouping

### ISSUE THREAD

**Issue by migueldeicaza** [xibbon/LaTerminal#7]
Feedback provided in https://dashboard.instabug.com/applications/swiftterm/live/bugs/6

Internal patch and tracking: https://github.com/xibbon/LaTerminalApp/issues/266

The idea is to deal with a lot of hosts by having an ability to tag or group the hosts.

I think that we can do this in a number of ways:

1. We could have every Host definition contain a "Group" field, which would indicate what this group belongs to.   And we would display the hosts in "Hosts" grouped by this field.
2. A little more aspirational: we could have Tags, which could be one or more strings, and we could group things by tags.   The idea with the tag that is different is that a Host could contain tags for different things, for example "work" and "observer", and when rendering the same host would appear under both "Work" and "DBServer" sections.

**Comment by iOSappssolutions** [comment]
@migueldeicaza are we going to let users define their own tags or use predefined tags in app or both

**Comment by migueldeicaza** [comment]
Let us go with a very simple model, as follows:

1. Host gets a new "tags" field, which is just a string, but we treat it as multiple values separated by commas.
2. On startup, we collect all the tags, by extracting this string, and splitting on commas.
3. We create a new TagEdit view that shows both an entry line at the top, and below a list of existing tags, and those tags that happen to be present on the string above, happen to be checked.   If the user edits the string, the list below updates automatically;   If the user checks or unchecks the entries, it gets reflected on the input line on top as well.
4. If we have tags defined, we show the Host listing by tags.   This also means that we might have duplicated hosts, for example if I tag a host as "linux,aws" it would show up both under "linux" and "aws"

**Comment by migueldeicaza** [comment]
Implemented, will be in the next major release
