### ISSUE TITLE
Feature: add bastion support

### ISSUE THREAD

**Issue by migueldeicaza** [xibbon/LaTerminal#8]
From: https://twitter.com/tcannonfodder/status/1572650172836114433 

Question: any chance you can support Gravitational teleport or SSH bastions in general?

Resources:
- Gravitational Teleport: https://github.com/gravitational/teleport

On SSH clients, this is possible:

```

Host proxy-ssh
  HostName proxy.domain.tld

Host private-ssh
  HostName 10.0.0.2
  ProxyJump proxy-ssh

It would be good to be able to do this kind of config to access those private internal addresses which aren’t available outside of our network. Especially if you can do SSH agent forwarding to use single credentials.
```

**Comment by tcannonfodder** [comment]
Related: https://azure.microsoft.com/en-us/products/azure-bastion/

**Comment by tcannonfodder** [comment]
I know Teleport is a Go program; can it be compiled & embedded inside the app?

**Comment by migueldeicaza** [comment]
(Note: work in progress in the `jump-host` branch)

**Comment by migueldeicaza** [comment]
Jumphosts/Bastion is now supported.

To use this:
* Define your bastion host and make sure you enter all the properties you want to use it
* Define the host that you want to reach from your jump host, with the address that can be reached from the jumphost/bastion.   Scroll to "Jump Host" and select the host that you defined in the step above.

It is available on Testflight, and would love if you folks could test it:

https://testflight.apple.com/join/cpPS8YnX
