### ISSUE TITLE
Improvement: Scrolling

### ISSUE THREAD

**Issue by rnsc** [xibbon/LaTerminal#9]
Currently scrolling through the screen is very slow so it requires a lot of swiping to just move up the screen.

**Comment by migueldeicaza** [comment]
Agreed, I have been working on improving this, but I want to get additional testing before I merge it (I will likely have the Testflight builds use this).

Here is a preview of what the new scrolling will be:

https://twitter.com/migueldeicaza/status/1568297405572956161?s=20

**Comment by rnsc** [comment]
That new scrolling is way better indeed! I don't know how they achieved it in Prompt, but your video with improved scrolling looks like the scrolling I'm getting in Prompt.

**Comment by migueldeicaza** [comment]
The new scrolling and selection are now available on testflight to try out:

https://testflight.apple.com/join/cpPS8YnX

**Comment by rnsc** [comment]
> The new scrolling and selection are now available on testflight to try out:
> 
> 
> 
> https://testflight.apple.com/join/cpPS8YnX

It's beautiful, thank you!
